### ISSUE TITLE
counter.li.org should redirect to linuxcounter.net

### ISSUE THREAD

**Issue by alvestrand** [alexloehner/linuxcounter.new#14]
This requires the owner of li.org to do something - he pulled the records into his zonefile long ago.

The listed tech contact is Michael Streib, dtype@dtype.org

**Comment by alexloehner** [comment]
email sent, thanks @alvestrand .

**Comment by alvestrand** [comment]
I sent one too - had a different email for him. Hope I used the right email for @alexloehner ....

**Comment by alexloehner** [comment]
Hey, thanks a lot!

Well, I have so many email addresses and that one was one that also
works, yes.

But for the future, better use alex.loehner@linux.com ... or alex@r3y.de

;-)



Am 02.05.2015 um 18:26 schrieb Harald Alvestrand:
> I sent one too - had a different email for him. Hope I used the right email for @alexloehner ....
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexloehner/linuxcounter.new/issues/14#issuecomment-98375766
> 

-- 
Best regards
ALEXANDER 'CRIZ' LÖHNER

Burgstr. 4d
D-78351 Bodman-Ludwigsafen
Germany

info: http://adf.ly/1Fo1it
portfolio: http://adf.ly/1Fo1sN
email: alex.loehner@linux.com
mobile: +49 151 234 620 80
facebook: http://adf.ly/1Fo1xl
google+: http://adf.ly/1Fo22K

icq: #43293804
msn: dma147@web.de
skype: alexloehner

homepage1: http://adf.ly/1FnA7P (Linux Counter)
homepage2: http://adf.ly/1Fo28d (APBoard)

https://linuxcounter.net/user/249600

_DONATE TO THE NEW LINUX COUNTER PROJECT:_
 --> http://adf.ly/1Fo2JS

**Comment by alexloehner** [comment]
works like a charm, thanks!
