### ISSUE TITLE
linuxcounter.org should redirect to linuxcounter.net

### ISSUE THREAD

**Issue by alvestrand** [alexloehner/linuxcounter.new#15]
This requires Harald Alvestrand, who owns linuxcounter.org, to update the nameservers for the domain (the old primary nameserver is currently offline).

**Comment by alexloehner** [comment]
Great! Thanks in advance @alvestrand !

**Comment by alexloehner** [comment]
@alvestrand   linuxcounter.org is still not working...

**Comment by alvestrand** [comment]
I redirected linuxcounter.com to linuxcounter.net - but have struck an oddity wrt www.linuxcounter.com: It is a CNAME to www.linuxcounter.net - but going to the page gives an "authentication required" rather than a Linux Counter page.

Something odd?

**Comment by alvestrand** [comment]
I did exactly the same thing for linuxcounter.org, and in that case, both redirects work as expected. @alexloehner can you check?

**Comment by alexloehner** [comment]
(www.)linuxcounter.org works without problems, thanks!
(www.)linuxcounter.com should also work in a few mintues, have to set the domain name in my vhost configuration...

**Comment by alexloehner** [comment]
Now, both are working! Thanks a lot! ;)
