### ISSUE TITLE
lico-update script is not updating my devices

### ISSUE THREAD

**Issue by brashley46** [alexloehner/linuxcounter.new#16]
user no. 548111 ... I run the script on each of my devices and the information does not update.

**Comment by alexloehner** [comment]
Hi,

which version of the script are you running? (lico-update.sh -v)
How did you run the script to send the data to the counter?
Did you get any error message or something that could help in determining the problem?

**Comment by brashley46** [comment]
brashley46@rossdesktop2:~$ lico-update.sh -v

# -------------------------------------------------------------------- #
#                        LiCo - The New Linux Counter Project          #
# Copyright (c) 2011 LiCo - The New Linux Counter Project              #
# This script is licensed under GNU GPL version 2.0 or above           #
# For more info, please visit: https://linuxcounter.net                #
# -------------------------------------------------------------------- #

 lico-update.sh version 0.3.20

brashley46@rossdesktop2:~$

**Comment by brashley46** [comment]
As for results, I get 
brashley46@rossdesktop2:~$ lico-update.sh -s
 The following data will be sent to the counter:

 ================================================================
 Script:           lico-update.sh version 0.3.20
 Hostname:         rossdesktop2
 update_key:       c4dSwFY7LUzRvFjs7LyHlviX
 onlinestatus:     online
 Distribution:     xubuntu
 Distrib Version:  15.04
 Counter Num:      548111
 Machine Num:      1004425
 Processor:        AMD Athlon(tm) 64 X2 Dual Core Processor 5000+
 CPU Frequency:    2200.000
 CPU flags:        fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch lbrv vmmcall
 Num cores:        2
 Num of Accounts:  5
 Num of users:     1
 Total diskspace:  957731368.000000
 Free diskspace:   605065524.000000
 Total RAM:        4007724
 Free RAM:         205636
 Total Swap:       35836
 Free Swap:        0
 Architecture:     i686
 Kernel:           3.19.0-15-generic
 Uptime:           3 days
 Load:              0.67, 0.63, 0.51
 ================================================================
 The string that sends the data consists of all information mentioned above
 separated by "##".

 Actually nothing was sent to the counter! Use -m to send the data.
brashley46@rossdesktop2:~$ lico-update.sh -m
brashley46@rossdesktop2:~$

**Comment by brashley46** [comment]
But the data on the machine's page does not update. This is not what we want.

**Comment by brashley46** [comment]
Same thing happens on the netbook; as for the Android devices I am running the script app as downloaded from the Google Play store.

**Comment by alexloehner** [comment]
@brashley46 Hello and thanks for your answers.
Please read this news:  https://www.linuxcounter.net/news/5

The old lico-update.sh script is not working anymore since the new website went online. The Android APP is also not working anymore and got removed from the play store already some weeks ago.

Please download the new lico-update.sh script here:
https://www.linuxcounter.net/download

A new version of the Android App will surely come... but it is not in development since now. First the new website must be completly finished.

Maybe there will be somebody who wants to create and maintain a new App for this.
