### ISSUE TITLE
New Android APP for the Linux Counter

### ISSUE THREAD

**Issue by alexloehner** [alexloehner/linuxcounter.new#18]
This is a major problem. Since the whole API has changed, the old Android APP is not working anymore and thus it got removed from the Play Store.

If anybody is able to create such an Android APP, I really would appreciate his or her help!

**Comment by elbarbudo** [comment]
I found an "official" LinuxCounter for Androïd on the PlayStore.
Is it yours?

Seems to be partially working.

1- does not ask for my ApiKey
2- on the LinuxCounter Site the "Last Update" column is updated, but NO other info

**Comment by alexloehner** [comment]
Hey,

that App is ours, yes... :)

1. The API Key is not needed for updating your machines, thus it does not ask for the API Key. For updating, the machine ID and the Machine Updatekey are needed.

2. Please open a new issue for this in the repository for the APP:  
https://github.com/alexloehner/linuxcounter.android.app
