### ISSUE TITLE
Linux kernel versions are late

### ISSUE THREAD

**Issue by elbarbudo** [alexloehner/linuxcounter.new#19]
Hello
I have an 3.13.0-52-generic kernel, but when I try to set it in my machine's profile, the latest kernel in the drop list is 3.13.0-24   (ID:1307).

Forcing 3.13.0-52 in the field is refused....

Is there a workeround?

**Comment by alexloehner** [comment]
Hey there... unfortunatly there is no workaround yet. I need to add newer kernel versions manually.

But I'll create something to add kernel versions by the community soon.

Please wait until this is done.

**Comment by alexloehner** [comment]
So... this is fixed since yesterday.

I've cleaned up the kernel versions and implemented a service that looks every 6 hours on kernel.org for the newest kernel versions and adds this to the database.

We are up to date now.

**Comment by elbarbudo** [comment]
Le 16/05/2015 10:37, Alexander Löhner a écrit :
>
> So... this is fixed since yesterday.
>
Great!
>
> I've cleaned up the kernel versions and implemented a service that 
> looks every 6 hours on kernel.org for the newest kernel versions and 
> adds this to the database.
>
> We are up to date now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alexloehner/linuxcounter.new/issues/19#issuecomment-102589692>.
>

-- 


------------------------------------------------------------------------


	

Ce courrier électronique ne contient aucun virus ou logiciel malveillant 
parce que Windows a été banni de cette machine.

In a world without fences and walls, who needs Gates or Windows?
