### ISSUE TITLE
Hostnames should be hideable

### ISSUE THREAD

**Issue by lhitc** [alexloehner/linuxcounter.new#2]
On the current ("old") LiCo Page, hostnames can be set to hidden.
This is currently not possible on the new site at test.linuxcounter.net.

Since the test site is publicly accessible and even promoted on social networks, and I definitely don't want to have internal hostnames on the net, I see this as a major privacy problem which will make me leave Linux Counter if it will not be resolved very soon.

Sorry for the clear wording, no pun intended.

**Comment by alexloehner** [comment]
The hostnames are now hidden by default and also for all existent machines in the database.
Please check and verify this.

Thanks for the report.

**Comment by alexloehner** [comment]
by the way, your clear words were absolutely understandable in this case... :)

**Comment by lhitc** [comment]
Checked and verified :-)
