### ISSUE TITLE
Cannot register new machine from Web page

### ISSUE THREAD

**Issue by alvestrand** [alexloehner/linuxcounter.new#21]
When going to this page:

https://www.linuxcounter.net/profile/machine/new

from menu, I expect either a form or instructions on how to run the client-side installer script.
I get a blank page. This seems wrong.

**Comment by alexloehner** [comment]
huu... I get the form to register a new machine... o.O
Btw. you need to be logged in, to register a new machine..

Can you please tell me, which browser and version you are using?

**Comment by alvestrand** [comment]
It was Chrome 42.0.2311.135 - of course, now it works :-(
I was logged in, but it was just a few minutes after I had reset my password.

**Comment by alexloehner** [comment]
hmm, strange... please watch that and tell me, if there are any further problems. I leave this ticket open for now.

**Comment by alexloehner** [comment]
hmm... okay... I close this for now. I guess, you have tried this when just a new version wehere deployed and the caches empty and such.
