### ISSUE TITLE
Location incorrectly set in profile

### ISSUE THREAD

**Issue by LdBarthel** [alexloehner/linuxcounter.new#25]
I've repeatedly attempted to set my location in the profile, but it consistently stores incorrect longitude/latitude settings.

My location is St. Charles, MO (38.782065, -90.485733). When I attempt to add it as "St. Charles" or "Saint Charles", I'm told it's already in the list--except it never appeared in the dialog before or after "adding". When I click on the "Show on Map" link, I've been taken to Arkansas and Maryland, depending on which spelling I used.

For the record, I've used the coordinates provided by Google Maps for the U.S. Post Office in St. Charles.

**Comment by alexloehner** [comment]
Hey there... unfortunatly the tool for adding a city needs to detect already existent cities in the same country. Since coordinates can be ver different for the same city (if it is a bigger city), I can not rely on the coordinates to check the existence. I only can rely on the country and the region. Since the region is empty for most of the cities in the database, only the country and the city name can be used for checking for existence.
This is why you get the message that it already exists.

I've added the city now manually to the database.

**Comment by LdBarthel** [comment]
That's very interesting. It explains why it returned false matches even though I included the region when making my submission. While including the null regions is appropriate for identifying potential matches, it is an error, in my opinion, to exclude the region from consideration entirely. (We're not even addressing the fact that Saint Charles and St. Charles are actually equivalent names...)

My expertise is in data analysis and integration.

I assume that you're collecting coordinates to simplify plotting user locations on a map. Given that 1 degree latitude is roughly 111 kilometers and 1 degree longitude is roughly 88 kilometers (at 38 degrees latitude), 0.01 degree is sufficient to map within +/- 1 kilometer. (At 5 significant figures, you'd be able to map where computers are in my house--at 6 significant figures you can tell which side of the room...).

Here's where you have to make a decision. If mapping is more important, then I would round to the nearest 0.01 degree and allow multiple entries for the same named city. (That would actually give you distribution of users within geographically larger cities.) If city names need to be significant, then I would allow only one entry per city name (per region, per country)--but I would then populate the table with an authoritative list (using coordinates of post offices or government seats) and validate the coordinates for any user entered cities.

At any rate, I think you should reformulate your location logic to include the region, otherwise you'll be adding a lot of US cities manually...
