### ISSUE TITLE
Old lico-update.sh

### ISSUE THREAD

**Issue by elbarbudo** [alexloehner/linuxcounter.new#32]
Hi

On an older system, I registered the ppa:alex-mieland/ppa repository and when I tried lico-update.sh, it started the OLD version 0.3.17ubuntu2 and was not able to upgrade to the new version.

I guess that this repository should be deleted

**Comment by alexloehner** [comment]
That is correct. the PPA is very old and not maintained anymore.
But if there is someone who wants to overtake the maintaining of the script or that PPA, he would be very welcome.
