### ISSUE TITLE
Reset password - I didn't receive email

### ISSUE THREAD

**Issue by craigarno** [alexloehner/linuxcounter.new#33]
I requested a reset password on the site, it looked like it didn't go smoothly, and I didn't receive an email

Not smooth means the site appeared to recognize my email "craig @ arno . com", but page didn't appear to complete.  I checked my mail (and spam folders) and found nothing.  I then refreshed the browser page to see what happened and was presented with the reset password page again.  I tried again and was informed "The password for this user has already been requested within the last 24 hours."

It would be nice if I'm not allowed to request a second reset if I could be given the option to "resend Reset-Password email".  As far as I know, there are no issues with my mail system.  It has been receiving email with the current configuration for years.

**Comment by alexloehner** [comment]
Can you please try that again? It should work. I've just tested it wthout problems.

**Comment by ptor** [comment]
Adding a 'me too'. Reset doesn't work, tried it twice (today). And I don't know why I even needed to, the pwd should be valid.. but in any case I'm stuck now. Email to my address should work as the reason I tried to check in was because of the info-email from alex.

**Comment by TinoM** [comment]
I've the same problem. It seems linuxcounter.net is currently listet on spamcop:
https://www.spamcop.net/w3m?action=checkblock&ip=79.133.40.162

Many Mailhosts (e.g.my own) use this to block spam => mails from linuxcounter do not arrive.

**Comment by craigarno** [comment]
Looks like I need a few more hours until SpamCop forgets about the block, after midnight here.  I use SpamCop and a few other RBL's to combat the ever escalating SPAM war.  So maybe tomorrow after I get off work.

**Comment by craigarno** [comment]
Reset Password works.  Looks like the problem was LinuxCounter listed in one of my active RBL's.

All my data is gone, so I put two of my machines back in.

**Comment by alexloehner** [comment]
Sorry guys... the problem indeed was the listing of the linux counter in spamcop. This got removed one and a half week ago, so emails should arrive again...
