### ISSUE TITLE
"Last Update" is not updated when using web-interface

### ISSUE THREAD

**Issue by Themroc** [alexloehner/linuxcounter.new#34]
After switching 2 machines to "online" (and correcting some more of the old data there) via the web-form, the "Last Update" column at the bottom of https://www.linuxcounter.net/profile/ still shows "2010-04-01".

**Comment by MervRenton** [comment]
Yes, I had the same experience. Last update does not change on Save with new details.

**Comment by roubert** [comment]
+1

**Comment by alexloehner** [comment]
Thanks, this problem just got solved.
