### ISSUE TITLE
No obvious way to lico-update.sh old machine data

### ISSUE THREAD

**Issue by Themroc** [alexloehner/linuxcounter.new#35]
I have some old data (from 1998) stored on linuxcounter.net, but found no documentation saying how to update it with the new lico-update.sh. After inserting the output of

dd if=/dev/random bs=1 count=256 | md5sum

into the "machine_updatekey" line of /root/.linuxcounter/xxx, the script said "[]> Data successfully sent.", but on the web-interface, i see no change.

**Comment by alexloehner** [comment]
Hi there,

when logging into your account and watching your own profile, you have the list of your machines at the bottom of your profile. There you also can see the machine_id and the machine_updatekey.
Inserting some random string as md5 hash isn't very senseful.

Please use the data provided by the application to update your machines as also described in the lico-update.sh when running with the -i paramater.

**Comment by Themroc** [comment]
I'm totally certain that the Update Key on the web-interface was empty when i tried this. Now there is some number... 

But there still is no "Update old machine" option in lico-update.sh. Looks like one has to:

    lico-update.sh -i
    3
    mcedit /root/.linuxcounter/MACHINE_NAME

give it the **machine_id** and **machine_updatekey** from the web-interface and finally

    lico-update.sh -m
