### ISSUE TITLE
Missing plausibilty checks in dates when editing profile 

### ISSUE THREAD

**Issue by lhitc** [alexloehner/linuxcounter.new#4]
When e.g. the day dropdown oft a date is empty, data is saved, but the date remains unchanged.
I would expect either the possibilty to save unsharp dates (like 09/1998) or an error message

**Comment by alexloehner** [comment]
oh, thanks for this report, this is of course a bug. I'll fix this soon.

**Comment by alexloehner** [comment]
This is now also fixed with the changes for issue #1
