### ISSUE TITLE
Can't create/update UpdateKey for very old (low number) ID's 

### ISSUE THREAD

**Issue by idef1x** [alexloehner/linuxcounter.new#40]
I've a few very old ID's of the counter project and decided to update them again since the project is revived again :)
However in the webportal those ID's don't contain an UpdateKey and is greyed out, so I can't create one ether :(
Deleting the ID and recreating a new ID with the lico-updater.sh would work, since newly machines added works find, but then I would loose the low ID number :(

**Comment by alexloehner** [comment]
I've just created updatekeys for ALL old machines that haven't one yet. So, please look into your account for your updatekeys now.
Thanks.

**Comment by idef1x** [comment]
Thanks it works fine now :)
