### ISSUE TITLE
Layout of machine list on mobile

### ISSUE THREAD

**Issue by lhitc** [alexloehner/linuxcounter.new#5]
When viewing with my tablet, the machine list in my profile is cut of on the right side.
There seems to be no zoom option to view all columns.
Happens in portrait and landscape mode, Browser is Firefox mobile.

**Comment by alexloehner** [comment]
This should now be fixed, please try and verify.

**Comment by lhitc** [comment]
Fixed for 7" tablet @1280x800 in landscape and portrait mode.
Also looks good on 5" phone @1920x1080 in landscape, but still cut off in portrait.

**Comment by alexloehner** [comment]
okay... on my samsung galaxy s4 it still is not working properly in portrait mode.
The strange thing: it doesn't seemt to get the latest css file. So I'll now try to install some kind of an android phone emulator, maybe the qemu thing...

**Comment by alexloehner** [comment]
okay... also in genymotion on a S4 in portrait mode it looks good now... on my real S4 it doesn't, so I assume there a caching problem with my real device.

Please test it again and verify, that it now looks good.

**Comment by lhitc** [comment]
All fine on tablet and smartphone now.
You left out the update key on small screens, which presumably makes sense.
