### ISSUE TITLE
Suggestions for "Statistics about the number of machines per country"

### ISSUE THREAD

**Issue by lhitc** [alexloehner/linuxcounter.new#6]
... at http://test.linuxcounter.net/statistics/machines

The list is very long, so maybe initially show the top 20 and have a button to expand is better.
Also percentage is rounded to 2 decimals which makes a lot of countries displayed as "0%". Maybe displaying "< 0.01%" is better in this case.

Edit: also the absolute numbers would be interesting here.

**Comment by alexloehner** [comment]
good ideas, thank you... I'll change that this way.

**Comment by alexloehner** [comment]
Okay... I've decided to make the machines per country paginated. So this should be fixed for now, not? ;)
