### ISSUE TITLE
No US cities in the type-ahead city field of the edit profile page and other values are not saved

### ISSUE THREAD

**Issue by pla1** [alexloehner/linuxcounter.new#7]
There doesn't appear to be any US cities in the type-ahead results of the city field on the edit profile page. If I ignore the type-ahead results and key my city, it is not saved.

**Comment by alexloehner** [comment]
Thanks for this issue! I'll create an additional button behind the city field with a plus sign in order to be able to add missing cities. This will be done tomorrow... now I'll go to bed  (11pm here)  :-P

**Comment by alexloehner** [comment]
@pla1  
Okay, this is implemented and tested.
Please also test it and verify that it is working. ;)

**Comment by pla1** [comment]
Doesn't work for me. I typed Summerville, SC, USA but the city remains Atlanta. ![Animated GIF] (http://i.imgur.com/xtZGvJg.gif)

**Comment by alexloehner** [comment]
@pla1  I have no clue, why the button with the plus sign on the right side of the city field isn't a button for you, but you need to click on that plus sign in order to add a new city that is missing.  :-)

Can you please tell me which browser you are using and which version? Then I maybe can fix the layout of that button.

**Comment by pla1** [comment]
Google Chrome Version 41.0.2272.118 (64-bit) on Ubuntu 14.04.2 LTS.

**Comment by alexloehner** [comment]
@pla1  I assume you already have tried to completly purge your cache and restart your browser, yes?
I'm asking, because I'm also using chrome on ubuntu and for me everything looks good. The plus sign is a nice button in the same hight as the input field for the city.

**Comment by pla1** [comment]
I didn't not clear my cache. Sorry about that. I went incognito and it worked fine. Thanks.
