### ISSUE TITLE
500 (internal server error) on new password entry for password reset

### ISSUE THREAD

**Issue by Algomorph** [alexloehner/linuxcounter.new#8]
Just letting you know. During the password reset procedure, after I used the link from the reset email & entered my new password (twice), I got a 500 error, although the password was successfully changed. Something must be amiss at the backend.

**Comment by alexloehner** [comment]
Thanks for reporting. I'll look into this soon.

**Comment by Algomorph** [comment]
P.S. this is for test.linuxcounter.net, so take your time :)

**Comment by alexloehner** [comment]
Thanks, but the test.linuxcounter.net has to go live in the next weeks (maybe days). So I need (want) to hurry. :-P

So, this is fixed now. Please try and verify.

**Comment by Algomorph** [comment]
I've verified, reset worked perfectly this time. Thanks for all the hard work on the website.
